#############################
#############################
## JavaScript Linter rules ##
#############################
#############################

env:
    browser: true
    jest: true
  
parser: babel-eslint
parserOptions:
    ecmaVersion: 2015
    sourceType: module
    ecmaFeatures:
        jsx : true

settings:
react:
    version: detect

plugins: ['react', 'react-hooks', 'prettier']

globals:
    Atomics: readonly
    SharedArrayBuffer: readonly

extends: ['eslint:recommended', 'plugin:react/recommended', 'plugin:prettier/recommended', 'airbnb', 'prettier', 'prettier/react']

rules: {}